#!/usr/bin/env python3
"""Build one illustrated six-language site from canonical Markdown and reviewed assets."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import tempfile
import uuid
from docs_build import build
from docs_check import check as check_output, directory as check_directory

ROOT = Path(__file__).resolve().parents[1]
MARKER = 'Generated by scripts/site.py\n'


def check(directory: Path) -> list[str]:
    if (directory / 'en/index.md').is_file():
        return check_output(build(directory.parent))
    return check_directory(directory)


def stage(files: dict[str, bytes], root: Path = ROOT) -> None:
    """Replace only owned generated output; retain the previous site for inspection."""
    check_output(files)
    output = root / '_site'
    review = root / '.maris-review'
    if review.is_symlink() or output.is_symlink():
        raise ValueError('Refusing a linked site destination')
    review.mkdir(exist_ok=True)
    lock = review / 'site-build.lock'
    lock.mkdir()  # Existing live/stale locks require inspection, not automatic deletion.
    previous = None
    try:
        if output.exists():
            marker = output / '.maris-generated'
            if marker.is_symlink() or not marker.is_file() or marker.read_text(encoding='utf-8') != MARKER:
                raise ValueError('Refusing to replace an unknown _site directory')
        with tempfile.TemporaryDirectory(prefix='site-build-', dir=review) as temporary:
            replacement = Path(temporary) / 'site'
            replacement.mkdir()
            for name, data in files.items():
                path = replacement / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
            (replacement / '.maris-generated').write_text(MARKER, encoding='utf-8')
            (replacement / '.nojekyll').touch()
            check_directory(replacement)
            if output.exists():
                previous = review / ('site-previous-' + uuid.uuid4().hex)
                output.rename(previous)
            try:
                replacement.rename(output)
            except OSError:
                if previous is not None and not output.exists():
                    previous.rename(output)
                raise
    finally:
        lock.rmdir()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = build(ROOT)
    names = check_output(files)
    if not args.check:
        stage(files)
    print(json.dumps({'validated_files': len(names), 'html_pages': sum(n.endswith('.html') for n in names),
                      'customer_languages': 6, 'customer_pages': 24,
                      'engineering_reference_language': 'en', 'actual_offline_ui_illustrations': 18,
                      'written': not args.check, 'remote_deployed': False}, indent=2))


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError, TypeError) as error:
        raise SystemExit(str(error)) from error
